{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-11-10 12:56:12,983+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1695, in unsubscribe\n    if symb not in self.scrips_count[self.channel_num]:\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-11-10 12:56:31,447+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1695, in unsubscribe\n    if symb not in self.scrips_count[self.channel_num]:\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-11-10 14:36:05,844+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1695, in unsubscribe\n    if symb not in self.scrips_count[self.channel_num]:\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'if|nse_cm|Nifty 50'","timestamp":"2023-11-10 14:43:09,223+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1109, in __datafeed_resp\n    self.resp[topic_name][\"symbol\"] = self.symbol_token[topic_name]\nKeyError: 'if|nse_cm|Nifty 50'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'if|nse_cm|Nifty 50'","timestamp":"2023-11-10 14:45:53,153+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1109, in __datafeed_resp\n    self.resp[topic_name][\"symbol\"] = self.symbol_token[topic_name]\nKeyError: 'if|nse_cm|Nifty 50'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-11-10 15:13:30,542+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1695, in unsubscribe\n    if symb not in self.scrips_count[self.channel_num]:\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'if|nse_cm|Nifty 50'","timestamp":"2023-11-10 15:17:42,234+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1109, in __datafeed_resp\n    self.resp[topic_name][\"symbol\"] = self.symbol_token[topic_name]\nKeyError: 'if|nse_cm|Nifty 50'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-11-10 15:28:33,270+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1695, in unsubscribe\n    if symb not in self.scrips_count[self.channel_num]:\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'if|nse_cm|Nifty 50'","timestamp":"2023-11-10 15:50:29,971+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1109, in __datafeed_resp\n    self.resp[topic_name][\"symbol\"] = self.symbol_token[topic_name]\nKeyError: 'if|nse_cm|Nifty 50'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-11-10 16:03:54,076+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\ajayb\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1695, in unsubscribe\n    if symb not in self.scrips_count[self.channel_num]:\nKeyError: 1","exception_name":"KeyError"}
